### ISSUE TITLE
Payload file '....\Acr.IO.rd.xml' does not exist.

### ISSUE THREAD

**Issue by RedTahr** [aritchie/io#2]
Hey, not sure if this is still in development, but just had a UWP project in a Xamarin.Forms PCL based solution give me this error:
Payload File 'C:\Users\<username>\.nuget\packages\Acr.IO\3.0.0\lib\uap10.0\Acr.IO\Properties\Acr.IO.rd.xml' does not exist.

I noticed some similar issues in UserDialogs repo, for a different xml file (xr.xml it might have been), so just created the extra two folders (Acr.IO\Properties) from where the package is installed and copied the Acr.IO.rd.xml there and its stopped complaining about that.

The NuGet dates make it look like you're still finding time to work on this, so thanks for your hard work. We've looked at the PCLStorage NuGet once or twice but just prefer some of the features of your solution.

**Comment by aritchie** [comment]
Give 3.0.1 on nuget a try
